[package]
name = "blobrust"
version = "0.1.0"
authors = ["daslocom"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2"
rand_core = "0.5.0"
rand_xorshift = "0.2.0"

[lib]
crate-type = ["cdylib"]
